version: "2"
services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - INTERFACE=eth0 #optional
    volumes:
      - config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.backend=https"
        - "traefik.port=9443"
        - "traefik.frontend.rule=Host:openvpn.kube.linktohack.com,opvn.kube.linktohack.com;PathPrefixStrip:/v2,/v3;AddPrefix:/api"
        - "traefik.frontend.auth.basic.users=Zm9vOiRhcHIxJE9GRzNYeWJwJGNrTDBGSERBa29YWUlsSDkuY3lzVDAK"
    imagePullSecrets:
      - name: openvpn-as-basic-auth
volumes:
  config:
    driver_opts:
      type: 'nfs'
      o: 'addr=192.168.1.1'
      device: '/root/data/com-linktohack-openvpn3'        