services:
  redmine:
    ClusterIP: {}
    NodePort: {}
    LoadBalancer: {}
    Ingress: {}
    Deployment:
      spec:
        template:
          spec:
            containers:
              - env:
                - name: REDMINE_DB_MYSQL
                  value: db
                - name: REDMINE_DB_PASSWORD
                  value: example
                image: redmine
                name: redmine
                volumeMounts:
                - mountPath: /usr/src/redmine/config/configuration.yml
                  name: redmine-0
                - mountPath: /usr/src/redmine/files
                  name: redmine-1
                imagePullPolicy: Always
volumes:
  db:
    PV:
      spec:
        capacity:
          storage: 10Gi
        persistentVolumeReclaimPolicy: Retain
    PVC:
      spec:
        resouces:
          requests:
            storage: 10Gi