services:
  redmine:
    ClusterIP: {}
    NodePort: {}
    LoadBalancer: {}
    Ingress: {}
    Deployment:
      spec:
        template:
          spec:
            containers:
              - name: override-namexxx
                imagePullPolicy: Always
volumes:
  db:
    PV:
      spec:
        capacity:
          storage: 10Gi
        persistentVolumeReclaimPolicy: Retain
    PVC:
      spec:
        resouces:
          requests:
            storage: 10Gi