version: '3.1'

services:
  redmine:
    image: redmine
    volumes:
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./files:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    networks:
      - default
      - web
    deploy:
      placement:
        constraints:
          - node.role != master
          - node.role == master
          - node.hostname == prod2
          - node.hostname != prod1
          - node.labels.xxx == yyy
          - node.labels.zzz
      labels:
        - 'traefik.frontend.rule=Host:redmine.kube.linktohack.com'
        - 'traefik.port=3000'
        - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
        - "traefik.frontend.auth.basic.users=admin:$apr1$nupaWZ6W$fl2XQNbZ6faN2xpTYZ73//"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.redirect.entryPoint=https"

  db:
    image: mysql:5.7
    volumes:
      - /root/data/com-linktohack-redmine/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.hostname == prod2

networks:
  web:
    external: true