version: '3.1'

services:
  redmine:
    image: redmine
    volumes:
      - redmine_files:/usr/src/redmine/files
    configs:
      - source: redmine_config
        target: /usr/src/redmine/config/configuration.yml
        mode: 0444
    secrets:
      - source: tested
        target: /tpm/tested
        mode: 0444
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    networks:
      - default
      - web
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role != master
          - node.role == master
          - node.hostname == prod2
          - node.hostname != prod1
          - node.labels.xxx == yyy
          - node.labels.zzz
      labels:
        - 'traefik.frontend.rule=Host:REDACTED'
        - 'traefik.port=3000'
        - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"
        - "traefik.frontend.auth.basic.users=REDACTED"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.redirect.entryPoint=https"
        - 'traefik.seg.frontend.rule=Host:REDACTED'
        - 'traefik.seg.port=3001'
    healthcheck:
      disabled: false
      test:
        - CMD
        - curl
        - -f
        - localhost:3000
      start_period: 1m30s
      interval: 30s
      timeout: 2s

  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.hostname == prod2

networks:
  web:
    external: true

volumes:
  redmine_config:
  redmine_files:
  db:
    driver_opts: 
      type: none
      device: /path/to/db

configs: 
  redmine_config:
    file: ./config.yml

secrets:
  tested:
    external: true
    name: with_external_name
    file: ./tested