services:
  redmine:
    ClusterIP: {}
    NodePort: {}
    LoadBalancer:
      tcp: {}
      upd: {}
    Ingress:
      default: {}
      seg: {}
    Auth:
      default: {}
      seg: {}
    Deployment:
      spec:
        template:
          spec:
            containers:
              - name: override-name
                imagePullPolicy: Always
volumes:
  db:
    PV:
      spec:
        capacity:
          storage: 10Gi
        persistentVolumeReclaimPolicy: Retain
    PVC:
      spec:
        resources:
          requests:
            storage: 10Gi
configs:
  redmine_config:
    ConfigMap:
      data:
        hello.yaml: there
secrets:
  tested:
    Secret:
      stringData: ""