version: '3.1'

services:
  redmine:
    image: redmine
    volumes:
      - /home/dev/link.bfast.redmine/redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - /home/dev/link.bfast.redmine/redmine/files:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    networks:
      - default
      - web
    deploy:
      placement:
        constraints:
          - node.hostname == prod2
      labels:
        - 'traefik.frontend.rule=Host:redmine.kube.linktohack.com'
        - 'traefik.port=3000'
        - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*"

  db:
    image: mysql:5.7
    volumes:
      - /home/dev/link.bfast.redmine/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.hostname == prod2

networks:
  web:
    external: true