{{- $Release := .Release -}}
{{- $Values := .Values -}}
{{- range $name, $service:= .Values.services }}
---
{{ include "stack.pv" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.pvc" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.service" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.ingress" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.deployment" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{- end -}}