{{- $Values := .Values -}}
{{- $Release := .Release -}}
---
{{ include "stack.pv" (dict "Values" $Values "Release" $Release) }}
{{- range $name, $service:= .Values.services }}
---
{{ include "stack.service.clusterIP" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.service.nodePort" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.service.loadBalancer" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.ingress" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
---
{{ include "stack.deployment" (dict "name" $name "service" $service "Values" $Values "Release" $Release) }}
{{- end -}}