{{- $Values := .Values -}}
{{- $Release := .Release -}}
{{/* volumes */}}
{{- range $volName, $volValue := include "stack.helpers.volumes" (dict "Values" $Values) | fromYaml -}}
{{- if not (get $volValue "dynamic") }}
---
{{- $pv := include "stack.pv" (dict "volName" $volName "volValue" $volValue "Values" $Values "Release" $Release) | fromYaml -}}
{{- $override := pluck "volumes" $Values | first | default dict | pluck (get $volValue "originalName") | first | default dict | pluck "PV" | first | default dict -}}
{{ $pv | merge $override | toYaml }}
{{- end -}}
{{/* volumes: pvc */}}
{{- if ne (get $volValue "kind") "StatefulSet" }}
---
{{- $pvc := include "stack.pvc" (dict "volName" $volName "volValue" $volValue) | fromYaml -}}
{{- $override := pluck "volumes" $Values | first | default dict | pluck (get $volValue "originalName") | first | default dict | pluck "PVC" | first | default dict -}}
{{ $pvc | merge $override | toYaml -}}
{{- end -}}
{{- end -}}
{{/* services */}}
{{- range $name, $service:= .Values.services }}
{{/* services: clusterIP */}}
{{- $clusterIP := include "stack.service.clusterIP" (dict "name" $name "service" $service "Values" $Values "Release" $Release) -}}
{{- $override := pluck "services" $Values | first | default dict | pluck $name | first | default dict | pluck "ClusterIP" | first | default dict -}}
{{- if $clusterIP }}
---
{{ $clusterIP | fromYaml | merge $override | toYaml }}
{{- end }}
{{/* services: nodePort */}}
{{- $nodePort := include "stack.service.nodePort" (dict "name" $name "service" $service "Values" $Values "Release" $Release) -}}
{{- $override := pluck "services" $Values | first | default dict | pluck $name | first | default dict | pluck "NodePort" | first | default dict -}}
{{- if $nodePort }}
---
{{ $nodePort  | fromYaml | merge $override | toYaml }}
{{- end }}
{{/* services: loadBalancer */}}
{{- $loadBalancer := include "stack.service.loadBalancer" (dict "name" $name "service" $service "Values" $Values "Release" $Release) -}}
{{- $override := pluck "services" $Values | first | default dict | pluck $name | first | default dict | pluck "LoadBalancer" | first | default dict -}}
{{- if $loadBalancer }}
---
{{ $loadBalancer | fromYaml | merge $override | toYaml }}
{{- end }}
{{/* services: ingress */}}
{{- $ingress := include "stack.ingress" (dict "name" $name "service" $service "Values" $Values "Release" $Release) -}}
{{- $override := pluck "services" $Values | first | default dict | pluck $name | first | default dict | pluck "Ingress" | first | default dict -}}
{{- if $ingress }}
---
{{ $ingress | fromYaml | merge $override | toYaml }}
{{- end }}
{{/* services: deployment */}}
{{- $deployment := include "stack.deployment" (dict "name" $name "service" $service "Values" $Values "Release" $Release) | fromYaml -}}
{{- $kind := get $deployment "kind" -}}
{{- $override := pluck "services" $Values | first | default dict | pluck $name | first | default dict | pluck $kind | first | default dict -}}
{{- if $deployment }}
---
{{ $deployment | merge $override | toYaml }}
{{- end -}}
{{- end -}}